version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    target-branch: develop
  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    target-branch: develop
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    target-branch: develop
  - package-ecosystem: docker
    directory: "/ui"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    target-branch: develop
  - package-ecosystem: docker
    directory: "/e2e"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    target-branch: develop
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    target-branch: develop
